name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install --workspaces=false
      - run: npm install --workspace apps/backend
      - run: npm install --workspace apps/frontend
      - run: npm run build --workspace @app/backend
      - run: npm run build --workspace frontend

